sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    # DOCKER_USER
    # DOCKER_PASSWORD

script:
  # build
  - docker build -t oanhnn/php-cli:7.0-$COMMIT        php-cli/7.0
  - docker build -t oanhnn/php-cli:7.0-xdebug-$COMMIT php-cli/7.0-xdebug
  - docker build -t oanhnn/php-fpm:7.0-$COMMIT        php-fpm/7.0
  - docker build -t oanhnn/php-fpm:7.0-xdebug-$COMMIT php-fpm/7.0-xdebug
  - docker build -t oanhnn/composer:$COMMIT           composer
  # run
  - docker run -d --name php-fpm-70         oanhnn/php-fpm:7.0-$COMMIT
  - docker run -d --name php-fpm-70-xdebug  oanhnn/php-fpm:7.0-xdebug-$COMMIT
  - docker run --rm oanhnn/php-cli:7.0-$COMMIT --version
  - docker run --rm oanhnn/php-cli:7.0-xdebug-$COMMIT --version
  - docker run --rm oanhnn/composer:$COMMIT --version
  # test
  - docker ps
  - ./docker-check.sh php-fpm-70
  - ./docker-check.sh php-fpm-70-xdebug
